/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import app.Application;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
/**
 *
 * @author marco
 */
public class InputDatosManual extends javax.swing.JDialog {
    private boolean soloInt;
    private String tipo;
    private String metodo;
    private boolean isDecimal;

    
    
    public void setSoloInt(boolean condicion){
        this.soloInt = condicion;
    }
    
    public boolean getSoloInt(){
        return soloInt;
    }
    
    public void setDecimal(boolean condicion){
        this.isDecimal = condicion;
    }
    
    public boolean isDecimal(){
        return isDecimal;
    }
    
    public void setTipo(String pTipo){
        this.tipo = pTipo;
    }
    
    public String getTipo(){
        return tipo;
    }
    
     public void setMetodo(String pMetodo){
        this.metodo = pMetodo;
    }
    
    public String getMetodo(){
        return metodo;
    }
    

    /**
     * Creates new form InputDatos
     * @param parent
     * @param modal
     */
    public InputDatosManual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenerarManual = new javax.swing.JButton();
        DatosManuales = new javax.swing.JTextField();
        LimpiarTextBox = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Valores por Ordenar");

        GenerarManual.setText("Generar");
        GenerarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarManualActionPerformed(evt);
            }
        });

        DatosManuales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DatosManuales.setText("(Ej: 1,2,3...)");
        DatosManuales.setToolTipText("");
        DatosManuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosManualesActionPerformed(evt);
            }
        });
        DatosManuales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DatosManualesKeyTyped(evt);
            }
        });

        LimpiarTextBox.setText("Limpiar");
        LimpiarTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTextBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenerarManual, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(DatosManuales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(LimpiarTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatosManuales, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LimpiarTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerarManual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarManualActionPerformed
        String datos = DatosManuales.getText();
        ArrayList<String> valores = new ArrayList<>(Arrays.asList(datos.split(",")));
        try {
            new Application(getTipo(),valores,getMetodo(),isDecimal());
        } catch (InterruptedException ex) {
            Logger.getLogger(InputDatosManual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(InputDatosManual.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_GenerarManualActionPerformed

    private void DatosManualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosManualesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatosManualesActionPerformed

    private void DatosManualesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatosManualesKeyTyped
        char input = evt.getKeyChar();
        if(getSoloInt()){
            if(!(Character.isDigit(input)) && input != ',') {
            evt.consume();    
            }
        }else{
            if((!Character.isDigit(input)) && input != ',' && input != '.') {
            evt.consume();
            }
        }
    }//GEN-LAST:event_DatosManualesKeyTyped

    private void LimpiarTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTextBoxActionPerformed
        DatosManuales.setText("");
    }//GEN-LAST:event_LimpiarTextBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DatosManuales;
    private javax.swing.JButton GenerarManual;
    private javax.swing.JButton LimpiarTextBox;
    // End of variables declaration//GEN-END:variables
}
