/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import Elementos.Elemento;
import Listas.Lista;
import Listas.ListaCir;
import Listas.ListaDob;
import Listas.ListaDobCir;
import app.Application;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;

/**
 *
 * @author marco
 */
public class InputDatosAleatorio extends javax.swing.JDialog {
    private boolean soloInt;
    private String tipo;
    private String metodo;
    private boolean isDecimal;

    
    
    public void setSoloInt(boolean condicion){
        this.soloInt = condicion;
    }
    
    public boolean getSoloInt(){
        return soloInt;
    }
    
    
     public void setDecimal(boolean condicion){
        this.isDecimal = condicion;
    }
    
    public boolean isDecimal(){
        return isDecimal;
    }
    
    public void setTipo(String pTipo){
        this.tipo = pTipo;
    }
    
    public String getTipo(){
        return tipo;
    }
    
     public void setMetodo(String pMetodo){
        this.metodo = pMetodo;
    }
    
    public String getMetodo(){
        return metodo;
    }
    /**
     * Creates new form InputDatos
     */
    public InputDatosAleatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenerarManual = new javax.swing.JButton();
        CantidadValores = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cantidad de datos?");

        GenerarManual.setText("Generar");
        GenerarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarManualActionPerformed(evt);
            }
        });

        CantidadValores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantidadValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadValoresActionPerformed(evt);
            }
        });
        CantidadValores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadValoresKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadValores)
                    .addComponent(GenerarManual, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CantidadValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GenerarManual)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarManualActionPerformed
        String cantidad = CantidadValores.getText();
        ArrayList<String> valores = new ArrayList<>();
        Random valor = new Random();
        for(int i=0;i<Integer.parseInt(cantidad);i++)
            valores.add(Integer.toString(valor.nextInt(100)));
         try {
            new Application(getTipo(),valores,getMetodo(),isDecimal());
        } catch (InterruptedException ex) {
            Logger.getLogger(InputDatosManual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(InputDatosAleatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
      //metodo para generar numeros aleatorios con cantidad como parametro
        this.setVisible(false);
    }//GEN-LAST:event_GenerarManualActionPerformed

    private void CantidadValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadValoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadValoresActionPerformed

    private void CantidadValoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadValoresKeyTyped
        char input = evt.getKeyChar();
        if(!(Character.isDigit(input)) || (input == KeyEvent.VK_BACKSPACE)){
        evt.consume();    
        }
    }//GEN-LAST:event_CantidadValoresKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadValores;
    private javax.swing.JButton GenerarManual;
    // End of variables declaration//GEN-END:variables
}
